---
abstract: 'useful features and typemaps for XS modules.'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '6.76'
  ExtUtils::ParseXS: '3.24'
  Test::Deep: '0'
  Test::More: '0'
  Test::Simple: '0.96'
configure_requires:
  ExtUtils::MakeMaker: '6.76'
  Panda::Install: v0.2.1
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.92, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Panda-XS
no_index:
  directory:
    - t
    - inc
requires:
  Panda::Install: v0.1.5
  perl: '5.018000'
version: v0.1.5
